# Generated by Django 3.0.5 on 2020-05-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
